hdfs:
  build: docker/hdfs
  hostname: hdfs
  container_name: hdfs
  ports:
    - 50070:50070
    - 50075:50075

sdc:
  build: docker/streamsets
  hostname: sdc
  container_name: sdc
  links:
    - hdfs
  ports:
    - 18630:18630

# Start DNS server so that HDFS download links work on the Linux host
dns:
  image: mgood/resolvable
  hostname: dns
  container_name: dns
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/resolv.conf:/tmp/resolv.conf


